-- e-NILAI schema updates
-- Jalankan skrip ini di Supabase SQL Editor untuk menyokong dashboard guru dan admin.

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS no_kp TEXT,
  ADD COLUMN IF NOT EXISTS jawatan TEXT,
  ADD COLUMN IF NOT EXISTS gred TEXT,
  ADD COLUMN IF NOT EXISTS opsyen TEXT;

CREATE TABLE IF NOT EXISTS public.pencerapan_kendiri (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'reviewed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pencerapan_kendiri_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.pencerapan_1 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'reviewed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pencerapan_1_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.pencerapan_2 (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  form_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'reviewed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pencerapan_2_user_id_key UNIQUE (user_id)
);

CREATE INDEX IF NOT EXISTS idx_pencerapan_kendiri_user_id ON public.pencerapan_kendiri (user_id);
CREATE INDEX IF NOT EXISTS idx_pencerapan_1_user_id ON public.pencerapan_1 (user_id);
CREATE INDEX IF NOT EXISTS idx_pencerapan_2_user_id ON public.pencerapan_2 (user_id);

ALTER TABLE public.pencerapan_kendiri ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pencerapan_1 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pencerapan_2 ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_kendiri' AND policyname = 'pencerapan_kendiri_owner_select'
  ) THEN
    CREATE POLICY pencerapan_kendiri_owner_select
      ON public.pencerapan_kendiri
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_kendiri' AND policyname = 'pencerapan_kendiri_owner_insert'
  ) THEN
    CREATE POLICY pencerapan_kendiri_owner_insert
      ON public.pencerapan_kendiri
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_kendiri' AND policyname = 'pencerapan_kendiri_owner_update'
  ) THEN
    CREATE POLICY pencerapan_kendiri_owner_update
      ON public.pencerapan_kendiri
      FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_kendiri' AND policyname = 'pencerapan_kendiri_admin_all'
  ) THEN
    CREATE POLICY pencerapan_kendiri_admin_all
      ON public.pencerapan_kendiri
      FOR ALL
      USING (EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
      ))
      WITH CHECK (EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
      ));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_1' AND policyname = 'pencerapan_1_owner_select'
  ) THEN
    CREATE POLICY pencerapan_1_owner_select
      ON public.pencerapan_1
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_1' AND policyname = 'pencerapan_1_owner_insert'
  ) THEN
    CREATE POLICY pencerapan_1_owner_insert
      ON public.pencerapan_1
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_1' AND policyname = 'pencerapan_1_owner_update'
  ) THEN
    CREATE POLICY pencerapan_1_owner_update
      ON public.pencerapan_1
      FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_1' AND policyname = 'pencerapan_1_admin_all'
  ) THEN
    CREATE POLICY pencerapan_1_admin_all
      ON public.pencerapan_1
      FOR ALL
      USING (EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
      ))
      WITH CHECK (EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
      ));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_2' AND policyname = 'pencerapan_2_owner_select'
  ) THEN
    CREATE POLICY pencerapan_2_owner_select
      ON public.pencerapan_2
      FOR SELECT
      USING (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_2' AND policyname = 'pencerapan_2_owner_insert'
  ) THEN
    CREATE POLICY pencerapan_2_owner_insert
      ON public.pencerapan_2
      FOR INSERT
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_2' AND policyname = 'pencerapan_2_owner_update'
  ) THEN
    CREATE POLICY pencerapan_2_owner_update
      ON public.pencerapan_2
      FOR UPDATE
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'pencerapan_2' AND policyname = 'pencerapan_2_admin_all'
  ) THEN
    CREATE POLICY pencerapan_2_admin_all
      ON public.pencerapan_2
      FOR ALL
      USING (EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
      ))
      WITH CHECK (EXISTS (
        SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
      ));
  END IF;
END $$;
